/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rmutk.pskw.martoh;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author admaun
 */
public class MainPanel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form MainPanel
     */
    private GrBoard GrB;
    private Timer Tmr;
    ArrayList<movement> MvA = new ArrayList<>();
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (MvA.isEmpty())
        {
            Tmr.stop();
            return;
        }
        GrB.MoveDisk(MvA.get(0).Disk, MvA.get(0).Src, MvA.get(0).Dst);
        MvA.remove(0);
    }
    
    
    public class movement {
        int Disk, Src, Dst;

        private movement(int i, int S, int D) {
            Disk = i;
            Src = S;
            Dst = D;
        }
    }
    

    
    public MainPanel() {
        initComponents();
        Tmr = new Timer(sldSpeed.getValue(), this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 //   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        sldSpeed = new javax.swing.JSlider();
        cmbNDisk = new javax.swing.JComboBox();

        btnStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnGo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        sldSpeed.setMajorTickSpacing(50);
        sldSpeed.setMaximum(1000);
        sldSpeed.setMinimum(100);
        sldSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSpeedStateChanged(evt);
            }
        });

        cmbNDisk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10 จาน", "9 จาน", "8 จาน", "7 จาน", "6 จาน", "5 จาน", "4 จาน" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(cmbNDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cmbNDisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(377, 377, 377))
        );
    }// </editor-fold>                        

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        GrB = new GrBoard(10-(int) (cmbNDisk.getSelectedIndex()));
        add(GrB);
        GrB.setBounds(20, 150, 800, 300);

    }                                        

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:

            HanoiMove(GrB.NOfDisk, 0, 2);
            Tmr.start();
    }                                     

    private void sldSpeedStateChanged(javax.swing.event.ChangeEvent evt) {                                      
        // TODO add your handling code here:

       Tmr.setInitialDelay(sldSpeed.getValue());
       Tmr.setDelay(sldSpeed.getValue());
       
    }                                     

    public void HanoiMove(int i, int S, int D) 
    {
        if (i==0)
            return;
        HanoiMove(i-1, S, 3-S-D);
 //       GrB.MoveDisk(10-i, S, D);
         MvA.add(new movement(GrB.NOfDisk-i, S, D));
         
        HanoiMove(i-1, 3-S-D, D);
        
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox cmbNDisk;
    private javax.swing.JSlider sldSpeed;
    // End of variables declaration                   
}


